Issue 4 user delete entry
jonahp001/code-journal pull request #8
Opened 2023-02-16 22:55 UTC by jonahp001

![Kapture 2023-02-16 at 14 50 26](https://user-images.githubusercontent.com/117235085/219506440-7ecbb9cb-4db4-46b2-814d-462eecd7b608.gif)

2023-02-17 14:11 UTC, robgmerrill requested changes
Very close! I've left a comment for what you should do at the end of the callback function on your confirm button.

2023-02-17 14:11 UTC, robgmerrill commented on js/main.js
> +  viewSwap('entries');
You will need to decrement data.entries.entryId by one. If you look in your gif you will see that this number keeps growing as you delete items and add items.

2023-02-19 03:46 UTC, jonahp001 commented
![Kapture 2023-02-18 at 19 42 55](https://user-images.githubusercontent.com/117235085/219916419-d3474953-70fe-4e47-bfb4-ea2e4e59afc2.gif)

fixed!!!! :)

2023-02-22 12:54 UTC, robgmerrill approved these changes
👍

2023-02-22 16:56 UTC, merged